name: vfx_dart
description: VerifiedX (VFX) Dart SDK for generating and managing keypairs.
version: 1.0.0
repository: https://github.com/VerifiedXBlockchain/VerifiedX-DartSDK
homepage: https://verifiedx.io

environment:
  sdk: ^3.5.3

dependencies:
  base58check: ^2.0.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  convert: ^3.1.2
  crypto: ^3.0.6
  hex: ^0.2.0
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
