name: vfx_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  base58check: ^2.0.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  convert: ^3.1.2
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
